Repository KDT5-FE-M6-team3/toy3, pull requests merged in 2023-07, with the labels that each got.

#7 Feat/routing and layout
  src/App.tsx
  src/components/MyDrawer.tsx
  src/components/MyLayout.tsx
  src/data/constants.ts
  src/index.css
  src/pages/About/index.tsx
Labels: Done

#11 Feat/accent color context
  .gitignore
  src/App.tsx
  src/components/MyDrawer.tsx
  src/context/AccentColorContext.tsx
  src/hooks/useAccentColor.ts
  src/index.css
  src/main.tsx
  src/utils/getAccentColorFromLocalStorage.ts
Labels: Done

#9 Feat/statistics
  index.html
  package-lock.json
  package.json
  src/assets/favicon.png
  src/components/MyDrawer.tsx
  src/data/constants.ts
  src/pages/Statistics/Chart.tsx
  src/pages/Statistics/MySelect.tsx
  src/pages/Statistics/MySkeleton.tsx
  src/pages/Statistics/index.tsx
  src/utils/getMonthLabels.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: Ing

#15 Feat/about page
  src/components/MyDrawer.tsx
  src/data/constants.ts
  src/pages/About/MyCard.tsx
  src/pages/About/index.tsx
  src/pages/Statistics/index.tsx
Labels: Done, Ing

#12 Feat/ Search & Modal
  package-lock.json
  package.json
  src/index.css
  src/pages/Home/Calendar.scss
  src/pages/Home/DailyExpenseModal.tsx
  src/pages/Home/DailyExpenseTable.tsx
  src/pages/Home/ExpenditureForm.tsx
  src/pages/Home/ExpenseModal.scss
  src/pages/Home/Search.tsx
  src/pages/Home/SearchResultModal.tsx
  src/pages/Home/getExpenses.tsx
  src/pages/Home/index.tsx
  src/types/expenses.ts
  src/types/search.ts
  src/utils/formatDateAndTime.ts
  src/utils/formatPaymentDate.ts
  tsconfig.json
  vite.config.ts
Labels: Ing

#21 Feat/calendar
  src/pages/Home/Calendar.scss
  src/pages/Home/DailyExpenseTable.tsx
  src/pages/Home/ExpenditureForm.tsx
  src/pages/Home/ExpenseModal.scss
  src/pages/Home/index.tsx
  src/utils/formatDateAndTime.ts
  vite.config.ts
Labels: Done

#20 Refactoring 하고 있는 중
  src/api/expenseAPIs.ts
  src/data/constants.ts
  src/pages/About/index.tsx
  src/pages/Statistics/Banner.tsx
  src/pages/Statistics/index.tsx
Labels: Ing

#19 Feat: 자동완성&모달 (미완성)
  package-lock.json
  src/index.css
  src/pages/Home/DailyExpenseTable.tsx
  src/pages/Home/ExpenditureForm.tsx
  src/pages/Home/Search.tsx
  src/pages/Home/SearchResultModal.tsx
  src/pages/Home/index.tsx
  src/types/search.ts
  src/utils/formatDateAndTime.ts
  src/utils/formatPaymentDate.ts
Labels: Ing

#23 Design: 소비금액 표기 단위변경
  src/pages/Home/DailyExpenseTable.tsx
  src/pages/Home/Search.tsx
  src/pages/Home/SearchResultModal.tsx
  src/pages/Home/index.tsx
Labels: Done
